// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJgaKjI3F4WbaBjRPsJutNnI5KEmj_tvU',
    appId: '1:828506609636:web:70a2a34b3ddc6558e619f1',
    messagingSenderId: '828506609636',
    projectId: 'silent-phone-misuse-detection',
    authDomain: 'silent-phone-misuse-detection.firebaseapp.com',
    storageBucket: 'silent-phone-misuse-detection.firebasestorage.app',
    measurementId: 'G-BZ3YHSX1MF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGMW5YNpqNhz4LS3LX05LLSj9uA1n945s',
    appId: '1:828506609636:android:8562c5781c18349de619f1',
    messagingSenderId: '828506609636',
    projectId: 'silent-phone-misuse-detection',
    storageBucket: 'silent-phone-misuse-detection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuU1XmmVm3KCf-ZqJKA4DYKVntOZrJoUU',
    appId: '1:828506609636:ios:857e473740f69860e619f1',
    messagingSenderId: '828506609636',
    projectId: 'silent-phone-misuse-detection',
    storageBucket: 'silent-phone-misuse-detection.firebasestorage.app',
    iosClientId: '828506609636-o4i0j7qukgucgs6p2733imnts6t7l14m.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuU1XmmVm3KCf-ZqJKA4DYKVntOZrJoUU',
    appId: '1:828506609636:ios:857e473740f69860e619f1',
    messagingSenderId: '828506609636',
    projectId: 'silent-phone-misuse-detection',
    storageBucket: 'silent-phone-misuse-detection.firebasestorage.app',
    iosClientId: '828506609636-o4i0j7qukgucgs6p2733imnts6t7l14m.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJgaKjI3F4WbaBjRPsJutNnI5KEmj_tvU',
    appId: '1:828506609636:web:4a0c83829d2ab1bbe619f1',
    messagingSenderId: '828506609636',
    projectId: 'silent-phone-misuse-detection',
    authDomain: 'silent-phone-misuse-detection.firebaseapp.com',
    storageBucket: 'silent-phone-misuse-detection.firebasestorage.app',
    measurementId: 'G-QVZEKB9805',
  );
}
